### ISSUE TITLE
Please add a EEVblog discussion thread

### ISSUE THREAD

**Issue by myjtag** [Rack-Robotics/Powercore-V2.0#1]
Hi
I highly recommend that you make a thread on EEVblog  forum, because there are lot's of interaction and highly skilled engineers there, to contribute and give feedback, Also I recommend you choose a better equipped MCU with SMPS control peripherals like STM32G431CBT6 which is affordable  enough and have lot's of great peripherals for controlling Advanced SMPS circuits. like ADC, DAC, Op-amp , comparator and Cordic engine

**Comment by John-RackRobotics** [comment]
While I am a fan of the EEVblog YouTube channel, I do not frequent the forum. For our application, we do not require the STM32G431CBT6. We are happy with the RP2040 for the Powercore V2.0.

**Comment by myjtag** [comment]
I highly recommend making a thread there, there is a hug and very active community there, they would help and contribute a lot.
